.PHONY: proto proto-clean lint

proto:
	protoc --go_out=. --go_opt=paths=source_relative \
       --go-grpc_out=. --go-grpc_opt=paths=source_relative \
       ./api/proto/file_service.proto

proto-clean:
	rm -f api/proto/*.pb.go

run-server:
	go run ./cmd/server/server.go

run-client:
	go run ./cmd/client/client.go $(filter-out $@,$(MAKECMDGOALS))

%:
	@: